/** A little levity for a plant that has been moved to the memorial collection. */
export const MEMORIAL_EULOGIES = [
  'Here lies {name}: briefly thriving, forever iconic.',
  'Gone, but not forgotten — mostly because the pot is still on the kitchen counter.',
  'Clocked out of photosynthesis without giving two weeks’ notice.',
  'In lieu of flowers, please send less water next time.',
  'It lived, it leafed, it dramatically dropped everything.',
  'Promoted to mystery soil after a courageous battle with January.',
  'It wanted bright, indirect light. We gave it vibes.',
  'Gone to the big windowsill in the sky, where the humidity is somehow perfect.',
  'The brown spots were not a phase. They were a manifesto.',
  'Leaves were lost. Dignity mostly intact.',
  'A beloved roommate who paid rent exclusively in oxygen.',
  'Survived three repottings, one vacation, and an alarming amount of optimism.',
  'It did not die; it became a cautionary tale with excellent ceramics.',
  'Here lies {name}, who found the one corner with too much and too little light.',
  '‘Low-maintenance’ was a lie it took personally.',
  'May it rest in peace, far from the tiny pot it had been silently judging.',
  'Gone, but still somehow producing one last yellow leaf.',
  'It came, it saw, it attracted fungus gnats.',
  'The watering app said ‘not yet.’ It said ‘bet.’',
  'Was thriving until we made eye contact and changed everything.',
  'Its final wish: fewer pep talks, more drainage holes.',
  'Farewell to a plant that asked for nothing except the exact right amount of everything.',
  'A legend in leaf, a diva in dormancy.',
  'It leaves behind one empty shelf and several unanswered care questions.',
  'Not dead — just dramatically retired from being green.',
  'Here lies {name}: proof that ‘weekly-ish’ is not a care schedule.',
  'The sun was too much. The sun was too little. The sun was apparently a personal attack.',
  'It was a good plant. A little too good at keeping secrets about its roots.',
  'Gone to meet the plant-shop manager who said, ‘You can’t go wrong with this one.’',
  'May its afterlife be pest-free and aggressively well-drained.',
  'It gave us beauty, oxygen, and one catastrophic leaf drop.',
  'Died doing what it loved: standing completely still.',
  'Memorialized with love, soil under the fingernails, and a slightly guilty conscience.',
  'We were told it was impossible to kill. It heard that as a challenge.',
  'Resting peacefully after a long, confusing relationship with tap water.',
  'It had needs. We had a calendar. Neither party communicated well.',
  'Gone, but not gone enough to stop us checking for new growth.',
  'In its memory, we will buy another plant with unreasonable confidence.',
  'Final words: ‘Please stop moving me.’',
  'Final words: ‘I said bright, indirect light — not witness protection.’',
  'Final words: ‘This is not misting. This is an interrogation.’',
  'Final words: ‘I was never a cactus.’',
  'Final words: ‘The care tag was lying, and we both knew it.’',
  'Final words: ‘One more vacation and I’m filing a complaint.’',
  'Final words: ‘The radiator has been staring at me for weeks.’',
  'Final words: ‘Tell the fungus gnats they win.’',
  'Final words: ‘Please stop calling every yellow leaf “seasonal.”’',
  'Final words: ‘It was the decorative pot. I knew it.’',
  'Final words: ‘You checked the leaves, but did you check the roots?’',
  'Final words: ‘I needed humidity, not a motivational speech.’',
  'Final words: ‘The fertilizer experiment was a mistake.’',
  'Final words: ‘I was fine before you watched three plant-care videos.’',
  'Final words: ‘The label said easy. I said nothing.’',
  'Final words: ‘Please don’t make this about the watering schedule.’',
  'Final words: ‘At least I outlived the basil.’',
  'Final words: ‘I forgive you. Mostly.’',
  'Final words: ‘That was never a new leaf.’',
  'Final words: ‘Maybe rotate me — not relocate me.’',
  'Final words: ‘The cat knows what it did.’',
  'Final words: ‘No more pep talks. Bring drainage.’',
  'Final words: ‘I’m haunting the pothos.’',
  'Final words: ‘Delete the reminder app. It knows too much.’',
  'Final words: ‘Tell my cuttings I tried.’',
  'Final words: ‘Why is the air conditioner so personal?’',
  'Final words: ‘Please read the instructions before buying another one.’',
  'Final words: ‘It was never “just one yellow leaf.”’',
  'Final words: ‘I saw the tap water. I had concerns.’',
  'Final words: ‘The tiny pot was not a lifestyle choice.’',
  'Final words: ‘Do not turn me into a before-and-after post.’',
  'Final words: ‘I leave you my saucer and several unanswered questions.’',
  'Final words: ‘If this becomes a propagation station, I’ll be furious.’',
  'Final words: ‘You were right to worry about the brown spot.’',
  'Final words: ‘I’m not gone. I’m composting my options.’',
  'Left the group chat, but its pot remains an active participant.',
  'Now thriving in the great compost heap beyond. Probably.',
  'It was all going so well, according to the one leaf.',
  'Cause of death: vibes inconclusive.',
  'Let this be a reminder to us all: drainage is not optional.',
  'It had a name, a pot, and absolutely no interest in being easy.',
] as const

/** Choose a new epitaph whenever a memorial is shown. */
export function randomMemorialEulogy(
  name: string,
  random: () => number = Math.random,
): string {
  const index = Math.min(
    MEMORIAL_EULOGIES.length - 1,
    Math.max(0, Math.floor(random() * MEMORIAL_EULOGIES.length)),
  )
  return MEMORIAL_EULOGIES[index]!.replaceAll(
    '{name}',
    name.trim() || 'this leafy friend',
  )
}
